name = "woocommerce-mcp-server"
main = "worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "mcps.evoltex.com.br/wc/*"
zone_name = "evoltex.com.br"